jq-linux64-1.6:
  size: 3953824
  object_id: f8c02ac9-587b-4bcd-6100-42a675bc6b61
  sha: sha256:af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
loki-linux64-2.7.4:
  size: 56614912
  object_id: 7689eced-7acd-4a68-7770-9fe2453c8a97
  sha: sha256:09a8cf0267e66d8b043d32a5117e5b97c447f8c90c25d23b85ac0efe7dd46da1