jq-linux64-1.8.1:
  size: 2255816
  object_id: 17dd9529-6c80-4a6f-7ce3-d26580b4bb61
  sha: sha256:020468de7539ce70ef1bceaf7cde2e8c4f2ca6c3afb84642aabc5c97d9fc2a0d
loki-linux64-3.5.8:
  size: 117956792
  object_id: 5b878c50-baae-4890-6297-f291f97200e6
  sha: sha256:a9c70d81ae983ca47defe8eff65bf833eee0932114fbfaa9556b1633ac0235f2
promtail-linux64-3.5.8:
  size: 110362192
  object_id: ca34b199-7636-48b7-78c5-2126bad9dadd
  sha: sha256:95c45765826a2da1571b4d792b2716fbc2ecbe9bc4fafdabd26fb3e9a6b8c220
